### ISSUE TITLE
Fix actions with empty list of actors

### ISSUE THREAD

**Issue by cswinter** [entity-neural-network/incubator#159]
`torch.distributions.categorical.Categorical` doesn't currently support a batch dimension (https://github.com/pytorch/pytorch/issues/71689), which causes action heads to crash when there are 0 actors: https://github.com/entity-neural-network/incubator/issues/155#issuecomment-1019637849

**Comment by vwxyzjn** [comment]
Hey @cswinter thanks for this fix! The scripts feel much more stable. I can run `poetry run python enn_ppo/enn_ppo/train.py env.id=GymMicrorts env.num_envs=4` without issue now.

However, I just ran into another maybe related bug when running larger number of envs such as `poetry run python enn_ppo/enn_ppo/train.py env.id=GymMicrorts env.num_envs=4`.

See  https://wandb.ai/entity-neural-network/enn-ppo/runs/14j1123s

```
Traceback (most recent call last):
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 1017, in <module>
    main()
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/hyperstate/command.py", line 86, in _f
    return f(cfg)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 1013, in main
    train(cfg)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 753, in train
    next_obs, next_done, metrics = rollout.run(
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/enn_ppo/enn_ppo/train.py", line 367, in run
    ) = self.agent.get_action_and_auxiliary(
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/rogue_net/rogue_net/actor.py", line 168, in get_action_and_auxiliary
    action, count, logprob, entropy, logit = action_head(
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/costa/Documents/go/src/github.com/vwxyzjn/incubator/rogue_net/rogue_net/head_creator.py", line 85, in forward
    dist = Categorical(logits=logits)
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/costa/.cache/pypoetry/virtualenvs/incubator-BZ1MCGMS-py3.9/lib/python3.9/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter logits (Tensor of shape (10, 12)) of distribution Categorical(logits: torch.Size([10, 12])) to satisfy the constraint IndependentConstraint(Real(), 1), but found invalid values:
tensor([[   -inf, -0.4215, -1.0674,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf,    -inf,    -inf],
        [   -inf, -0.3849, -1.1411,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf,    -inf,    -inf],
        [-0.1876, -2.1427, -2.9235,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf,    -inf,    -inf],
        [   -inf, -0.4179, -1.0742,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf,    -inf,    -inf],
        [   -inf, -0.3849, -1.1411,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf,    -inf,    -inf],
        [    nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
             nan,     nan,     nan,     nan],
        [   -inf,    -inf, -6.3404, -3.5986,    -inf,    -inf,    -inf,    -inf,
            -inf, -0.0296,    -inf,    -inf],
        [   -inf,  0.0000,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf,    -inf,    -inf],
        [-3.6184,    -inf, -6.3346,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf, -0.0290,    -inf,    -inf],
        [   -inf, -0.4293, -1.0526,    -inf,    -inf,    -inf,    -inf,    -inf,
            -inf,    -inf,    -inf,    -inf]], device='cuda:0')
```

**Comment by cswinter** [comment]
It turns out this is actually a different issue, tracked here: https://github.com/entity-neural-network/incubator/issues/186
